# Site wide configuration
title: Tuna Meral
locale: en_US

# Site owner information
owner:
  name: Tuna Meral
  avatar: bio-avatar.jpg
  bio: "PhD Student @ VT • Vision Generative AI, Diffusion & Autoregressive Models"
  email: tunahansmeral at gmail dot com
  twitter: tunahansalih
  linkedin: tmeral
  github: tunahansalih
  instagram: howtunasees
  google:
    scholar: 5ZAhf5IAAAAJ
  stackoverflow: 2959389/tuna-meral

# Theme colors
highlight-color: '#CC0000'
lowlight-color: '#000'

# Jekyll configuration
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# Markdown settings
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Build settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude files from processing
exclude: [
  "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb",
  "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec",
  "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"
]
